#' @noRd
.onLoad <- function(libname, pkgname) {
  register_rule(rule_structure_required_dirs())
  register_rule(rule_dependency_forbidden())
  register_rule(rule_dependency_circular())
  register_rule(rule_complexity_cyclomatic())
  register_rule(rule_complexity_function_length())
  register_rule(rule_complexity_file_length())
  register_rule(rule_antipattern_global_assign())
  register_rule(rule_antipattern_assign())
  register_rule(rule_antipattern_setwd())
  register_rule(rule_antipattern_hardcoded_path())
  register_rule(rule_documentation_missing())
  register_rule(rule_testing_missing_tests())
  register_rule(rule_package_deprecated_api())
  register_rule(rule_ecosystem_shiny_structure())
  register_rule(rule_ecosystem_targets_structure())
  register_rule(rule_ecosystem_plumber_structure())
  invisible()
}
